insert into chorecategories (chorecat,chorecatdes,sortorder) values (1, 'Dailly Clean', 1),
(2, 'Weekly clean', 2),
(3, 'Vacuming', 3),
(4, 'Cleaning kitchen/bathroom', 4), 
(5, 'Heavy duty kitchen cleaning (oven/fridge)', 5),
(6, 'Washing dishes', 6),
(7, 'Washing clothes/bedding', 7), 
(8, 'Ironing', 8),(9, 'Doing/supervising homework', 9),
(10, 'Childcare', 10),
(11, 'Taking children to clubs/games/tution', 11),
(12, 'Arranging play dates', 12), 
(13, 'Organising birthday parties', 13), 
(14, 'Looking after children at evenings and weekends', 14),
(15, 'Feeding/Walking pets', 15),
(16, 'Preparing meals', 16),
(17, 'Watering plants', 17),
(18, 'Mowing the lawn', 18),
(19, 'Weeding the garden', 19),
(20, 'Taking out the trash', 20),
(21, 'Car Washing', 21),
(22, 'Washing windows', 22),
(23, 'Bathing pets', 23),
(24, 'Clean refrigerator', 24),
(25, 'Change air filters on furnace or air conditioner', 25),
(26, 'Winterize the house', 26),
(27, 'Clean garage', 27),
(28, 'Prune trees and shrubs', 28)
